// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Account defines model for Account.
type Account struct {
	// Amount Amount of money in the account
	Amount string `json:"amount"`

	// Id Id of the account
	Id openapi_types.UUID `json:"id"`

	// Self URL to the account
	Self string `json:"self"`
}

// ErrorResponse Error response following RFC9457.
type ErrorResponse struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`
}

// MoneyTransferRequest Money transfer request
type MoneyTransferRequest struct {
	Amount string `json:"amount"`
}

// MoneyTransferResponse Money transfer response
type MoneyTransferResponse struct {
	// AccountGiver Id of the account giver
	AccountGiver openapi_types.UUID `json:"accountGiver"`

	// AccountReceiver Id of the account receiver
	AccountReceiver openapi_types.UUID `json:"accountReceiver"`
	Amount          string             `json:"amount"`
}

// Page defines model for Page.
type Page struct {
	// Next URL to the next page
	Next string `json:"next"`

	// Number Current page number
	Number int `json:"number"`

	// Prev URL to the previous page
	Prev string `json:"prev"`

	// Self URL to the current page
	Self string `json:"self"`

	// Size Size of the page
	Size int `json:"size"`

	// TotalCount Total number of elements in the page
	TotalCount int64 `json:"totalCount"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// PageAccounts defines model for PageAccounts.
type PageAccounts struct {
	Accounts []Account `json:"accounts"`
	Page     Page      `json:"page"`
}

// GetAccountsParams defines parameters for GetAccounts.
type GetAccountsParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Size Page size
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// TransferMoneyParams defines parameters for TransferMoney.
type TransferMoneyParams struct {
	// IdempotencyKey Idempotence key
	IdempotencyKey *openapi_types.UUID `json:"Idempotency-Key,omitempty"`
}

// TransferMoneyJSONRequestBody defines body for TransferMoney for application/json ContentType.
type TransferMoneyJSONRequestBody = MoneyTransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get accounts endpoint
	// (GET /api/v1/accounts)
	GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams)
	// Get account endpoint
	// (GET /api/v1/accounts/{id})
	GetAccount(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Transfer money between accounts
	// (POST /api/v1/{accountGiver}/transfers/{accountReceiver})
	TransferMoney(w http.ResponseWriter, r *http.Request, accountGiver openapi_types.UUID, accountReceiver openapi_types.UUID, params TransferMoneyParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get accounts endpoint
// (GET /api/v1/accounts)
func (_ Unimplemented) GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get account endpoint
// (GET /api/v1/accounts/{id})
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transfer money between accounts
// (POST /api/v1/{accountGiver}/transfers/{accountReceiver})
func (_ Unimplemented) TransferMoney(w http.ResponseWriter, r *http.Request, accountGiver openapi_types.UUID, accountReceiver openapi_types.UUID, params TransferMoneyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccounts(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferMoney operation middleware
func (siw *ServerInterfaceWrapper) TransferMoney(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "accountGiver" -------------
	var accountGiver openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "accountGiver", chi.URLParam(r, "accountGiver"), &accountGiver, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountGiver", Err: err})
		return
	}

	// ------------- Path parameter "accountReceiver" -------------
	var accountReceiver openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "accountReceiver", chi.URLParam(r, "accountReceiver"), &accountReceiver, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountReceiver", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params TransferMoneyParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferMoney(w, r, accountGiver, accountReceiver, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounts", wrapper.GetAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounts/{id}", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/{accountGiver}/transfers/{accountReceiver}", wrapper.TransferMoney)
	})

	return r
}

type GetAccountsRequestObject struct {
	Params GetAccountsParams
}

type GetAccountsResponseObject interface {
	VisitGetAccountsResponse(w http.ResponseWriter) error
}

type GetAccounts200JSONResponse PageAccounts

func (response GetAccounts200JSONResponse) VisitGetAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccounts400ApplicationProblemPlusJSONResponse ErrorResponse

func (response GetAccounts400ApplicationProblemPlusJSONResponse) VisitGetAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAccounts500ApplicationProblemPlusJSONResponse ErrorResponse

func (response GetAccounts500ApplicationProblemPlusJSONResponse) VisitGetAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountRequestObject struct {
	Id openapi_types.UUID `json:"id,omitempty"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse Account

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccount4XXApplicationProblemPlusJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetAccount4XXApplicationProblemPlusJSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetAccount500ApplicationProblemPlusJSONResponse ErrorResponse

func (response GetAccount500ApplicationProblemPlusJSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type TransferMoneyRequestObject struct {
	AccountGiver    openapi_types.UUID `json:"accountGiver,omitempty"`
	AccountReceiver openapi_types.UUID `json:"accountReceiver,omitempty"`
	Params          TransferMoneyParams
	Body            *TransferMoneyJSONRequestBody
}

type TransferMoneyResponseObject interface {
	VisitTransferMoneyResponse(w http.ResponseWriter) error
}

type TransferMoney200JSONResponse MoneyTransferResponse

func (response TransferMoney200JSONResponse) VisitTransferMoneyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TransferMoney400ApplicationProblemPlusJSONResponse ErrorResponse

func (response TransferMoney400ApplicationProblemPlusJSONResponse) VisitTransferMoneyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TransferMoney500ApplicationProblemPlusJSONResponse ErrorResponse

func (response TransferMoney500ApplicationProblemPlusJSONResponse) VisitTransferMoneyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get accounts endpoint
	// (GET /api/v1/accounts)
	GetAccounts(ctx context.Context, request GetAccountsRequestObject) (GetAccountsResponseObject, error)
	// Get account endpoint
	// (GET /api/v1/accounts/{id})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// Transfer money between accounts
	// (POST /api/v1/{accountGiver}/transfers/{accountReceiver})
	TransferMoney(ctx context.Context, request TransferMoneyRequestObject) (TransferMoneyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAccounts operation middleware
func (sh *strictHandler) GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams) {
	var request GetAccountsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccounts(ctx, request.(GetAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountsResponseObject); ok {
		if err := validResponse.VisitGetAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAccountRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferMoney operation middleware
func (sh *strictHandler) TransferMoney(w http.ResponseWriter, r *http.Request, accountGiver openapi_types.UUID, accountReceiver openapi_types.UUID, params TransferMoneyParams) {
	var request TransferMoneyRequestObject

	request.AccountGiver = accountGiver
	request.AccountReceiver = accountReceiver
	request.Params = params

	var body TransferMoneyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferMoney(ctx, request.(TransferMoneyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferMoney")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferMoneyResponseObject); ok {
		if err := validResponse.VisitTransferMoneyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYT4/bthP9KgR/v1u1lpMmbaJT07TdBk2AxWbbBFjsgZZGNlP+y5By1jH83QtSlGxL",
	"sqwNGvSSm1ccvhkO35sZ7pbmWhqtQDlLsy21+QokCz9f5LmulPM/DWoD6DiEBSab7wXYHLlxXCua0Rfh",
	"O9ElkVrBhnBF3AoIizgJdRsDNKPWIVdLuksoL/oorwqPcLyx1CiZoxmtKl4MAVkQZR/qz+vXxOmTWMj7",
	"ULuEInysOEJBs9saN8SZNMe+a/foxQfInXf/K6LGa7BGKwv9OMIywbhOSi2E/sTVklz/9vL5k6c/zmjS",
	"SXEBjnExkGKyqiRTFwisYAsBBO6NYIr5ZWIN5LzkeX1mbonO8woRVA5NSg3qhQA5G8yhY66yfZ83KyC/",
	"39xckdqA5LoAsgQFyBwUZLEJyBr5kitiAdeApNQ4IQTJ7rmsJM2ePn+eUMlV/dej+bwNjysHS0Afn+NO",
	"wFBK7EqjS7qZsZWUDDcdt8Tjzs7ee+0rae6hTc7Q5b/xZL9BpmwJeA0fK7AD4ghWxEUzgtEuOamt8QBH",
	"yNiJ5xQpewFFw15EtXIu+RpwglrJMhhO0GzccA05TMXGxnYK/NRMHp6vH9Wo7q/YEvr1UcG9Gy1G3oAY",
	"v/dcOUqoquRiKDkvg6xqGBKNDjQ0qCCDsB4NzBtwXdmpwZ0tu/lBlFPw+OcBpr7ln/fVowba14rBSqEd",
	"Ey+Hm9SNX4sJ86AgQPrm13SrbqRcuR+enM1s8OjZYM97NMGsj9JtPT4XR2c5ctMyI2maVLjdpGZfQkuO",
	"obwIZk9zN7Z4O9DjD1a4Axl+/B+hpBn9X7qfGdI4MKTNtLBrXTFEtgm0iyoZ2x6UdEKa/rABo38Mv4Or",
	"Unv4XCvH8nDlIEP3pJKpCkShVQ5CMnTa/rT0S7NcS58qJj3Ym2BFfglm5E2wowmt0EOsnDM2S9Mld6tq",
	"4TemNSpDB/50x5d9qck7WJDXbKMrlxCmCNwzaUQgMCNx+Qq1j5+IYBbaUd3c6KW+eAeLi3o/Tega0NbI",
	"89l89sg71AYUM5xm9PvwySfHrcIFpczwdP0oPby9JQyo4BIcYUI0hdX6EPz1h0HiVVFbvDhMPzIJDtDS",
	"7LYLdnVUgrj/9LEC3OwzHEVVX7aPZkxNu2TQQdTDEHxc2sMXULJKOJo9nh9OGfPxwrG78/Sr22BI3eP5",
	"vCEW1LWEGSN4HrKUfrA+uO2B23MEbxMaeNspclWeg7VlJdpWPPO3/WQ0hjjVfPewWI7H1YFg/mKCF/VQ",
	"GWx9IE//i0BeKQeomCBv67kyRhNaT14hdxua3d4lNA57DbNjngmowmhel062tEc15c6jdAWTbnmxG1dN",
	"HEUWG8KLMdmcU000I2F6Caz2Mt6TOnzfp/HMvPNVudvW9gfQ9v37b7T9MtpOZ+32cHbdpc0sb9uFZooN",
	"lDZ66F3SPBTim71ELdtAnD54Nx/zvNkWXhFTqR6eBicJ3xnEp1M/2Y7AHQzyD0LsPkVAGu3CO/bvcODg",
	"cQWsCNDR595sc/FHMHuggMOj8GddbP417Q6+TnfHk5bDCnZfsX4Mv0gHdNOS0bZl5VsT/IJq0hH1Atwn",
	"AEUO5umhwhIAvYchDb/WOROkgDUIbfyLKf6rZ3Y0KWdpKrzhSluXbY1Gt/NDLEPOFqImlv94NKPRZ/Nn",
	"c5pM9Ef8fu8UlB/jbuvdPvq79lQn6s9+HrC9MmHp7m73TwAAAP//6nYOaA0VAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
