// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package rest

import (
	"net/url"
	"strings"
)

type GetAccountsEndpoint struct{}

type GetAccountsEndpointQueryParams struct {
	Page string
	Size string
}

func (q GetAccountsEndpointQueryParams) ToQueryString() string {
	values := url.Values{}
	if q.Page != "" {
		values.Set("page", q.Page)
	}
	if q.Size != "" {
		values.Set("size", q.Size)
	}
	return values.Encode()
}

func (p GetAccountsEndpoint) Path(queryParams GetAccountsEndpointQueryParams) string {
	message := "/api/v1/accounts"
	if queryString := queryParams.ToQueryString(); queryString != "" {
		message = message + "?" + queryString
	}
	return message
}

type GetAccountEndpoint struct{}

func (p GetAccountEndpoint) Path(id string) string {
	message := "/api/v1/accounts/{id}"
	message = strings.Replace(message, "{id}", id, -1)
	return message
}

type Paths struct {
	GetAccountEndpoint  GetAccountEndpoint
	GetAccountsEndpoint GetAccountsEndpoint
}
