// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID     uuid.UUID
	Amount float64
}

type Transfer struct {
	ID            uuid.UUID
	Timestamp     time.Time
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        float64
}
