// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, amount FROM accounts
    WHERE id = ?1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.Amount)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT id, amount FROM accounts
    LIMIT ?2
    OFFSET ?1
`

type GetAccountsParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) GetAccounts(ctx context.Context, arg GetAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccounts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAmount = `-- name: SaveAmount :exec
UPDATE accounts SET amount = ?1 WHERE id = ?2
`

type SaveAmountParams struct {
	Amount float64
	ID     uuid.UUID
}

func (q *Queries) SaveAmount(ctx context.Context, arg SaveAmountParams) error {
	_, err := q.db.ExecContext(ctx, saveAmount, arg.Amount, arg.ID)
	return err
}
